Repository cse-sim/cse, pull requests merged in 2022-04, with the labels that each got.

#214 Add explicit model for WSHPs
  doc/src/records/rsys.md
  src/CNDEFNS.H
  src/CNDTYPES.DEF
  src/CNLOADS.CPP
  src/CNRECS.DEF
  src/CNZTU.CPP
  src/CVPAK.CPP
  src/RCDEF.CPP
  test/CMakeLists.txt
  test/ref/ACTEST1BL.REP
  test/ref/WSHP.REP
  test/wshp.cse
Labels: enhancement, building science

#181 Address documentation misalignment
  .github/workflows/build-and-test.yml
  doc/README.md
  doc/lib/coverage_check.rb
  doc/lib/section_index.rb
  doc/rakefile.rb
  doc/src/cse-user-manual.yaml
  doc/src/records/airhandler.md
  doc/src/records/boiler.md
  doc/src/records/chiller.md
  doc/src/records/coolplant.md
  doc/src/records/descond.md
  doc/src/records/dhwheater-doc.md
  doc/src/records/dhwheater.md
  doc/src/records/dhwloopbranch.md
  doc/src/records/dhwloopheater.md
  doc/src/records/dhwsolarcollector.md
  doc/src/records/dhwsolarsys.md
  doc/src/records/dhwsys.md
  doc/src/records/dhwtank.md
  doc/src/records/doas.md
  doc/src/records/ductseg.md
  doc/src/records/export.md
  doc/src/records/gain.md
  doc/src/records/heatplant.md
  doc/src/records/importfile.md
  doc/src/records/inverse.md
  doc/src/records/loadmeter.md
  doc/src/records/meter.md
  doc/src/records/report.md
  doc/src/records/rsys.md
  doc/src/records/terminal.md
  doc/src/records/top-members.md
  doc/test/coverage_check_test.rb
  src/CNCULT.CPP
  src/CNRECS.DEF
Labels: documentation, maintenance

#183 Move all tables to use embedded ruby
  doc/src/records/afmeter.md
  doc/src/records/airhandler.md
  doc/src/records/battery.md
  doc/src/records/boiler.md
  doc/src/records/chiller.md
  doc/src/records/construction.md
  doc/src/records/coolplant.md
  doc/src/records/dhwdayuse.md
  doc/src/records/dhwheater-doc.md
  doc/src/records/dhwheatrec.md
  doc/src/records/dhwloop.md
  doc/src/records/dhwloopbranch.md
  doc/src/records/dhwlooppump.md
  doc/src/records/dhwloopseg.md
  doc/src/records/dhwmeter.md
  doc/src/records/dhwpump.md
  doc/src/records/dhwsolarcollector.md
  doc/src/records/dhwsolarsys.md
  doc/src/records/dhwsys.md
  doc/src/records/dhwtank.md
  doc/src/records/dhwuse.md
  doc/src/records/door.md
  doc/src/records/ductseg.md
  doc/src/records/export.md
  doc/src/records/exportcol.md
  doc/src/records/exportfile.md
  doc/src/records/fndblock.md
  doc/src/records/foundation.md
  doc/src/records/gain.md
  doc/src/records/glazetype.md
  doc/src/records/heatplant.md
  doc/src/records/holiday.md
  doc/src/records/importfile.md
  doc/src/records/izxfer.md
  doc/src/records/layer.md
  doc/src/records/loadmeter.md
  doc/src/records/material.md
  doc/src/records/meter.md
  doc/src/records/perimeter.md
  doc/src/records/pvarray.md
  doc/src/records/report.md
  doc/src/records/reportcol.md
  doc/src/records/reportfile.md
  doc/src/records/rsys.md
  doc/src/records/sgdist.md
  doc/src/records/shade.md
  doc/src/records/shadex.md
  doc/src/records/surface.md
  doc/src/records/terminal.md
  doc/src/records/top-members.md
  doc/src/records/window.md
  doc/src/records/zone.md
Labels: enhancement, documentation

#235 Exclude git from documentation artifact.
  .github/workflows/build-and-test.yml
Labels: maintenance, 2 - medium priority

#224 Adds autosize to documentation
  doc/src/input-structure.md
  doc/src/records/airhandler.md
  doc/src/records/terminal.md
Labels: enhancement, documentation
