Repository cse-sim/cse, pull requests merged in 2022-11, with the labels that each got.

#257 Replace windows convert case functions
  src/RCDEF/rcdef.cpp
  src/brfw.cpp
  src/cse.cpp
  src/strpak.cpp
  src/strpak.h
  src/xiopak.cpp
  test/unit/strpak.unit.cpp
Labels: enhancement, 2 - medium priority, multi-platform

#346 Make native preprocessor definitions for build configurations
  .gitignore
  CMakeLists.txt
  cmake/BuildFlags.cmake
  src/cnglob.h
  src/dmpak.cpp
  src/envpak.cpp
  src/rmkerr.cpp
  src/strpak.cpp
  src/strpak.h
Labels: maintenance

#286 Rmkerr multiplatform upgrade
  src/rmkerr.cpp
Labels: enhancement, multi-platform

#292 Replace char filename buffer
  src/RCDEF/rcdef.cpp
  src/brfw.h
  src/cncult4.cpp
  src/cnglob.h
  src/cse.cpp
  src/envpak.cpp
  src/pp.cpp
  src/rmkerr.cpp
  src/strpak.cpp
  src/xiopak.cpp
  src/xiopak.h
  src/xmodule.h
Labels: enhancement, multi-platform

#278 Envpak multiplatform upgrade - port floating point error handling to Linux
  src/brfw.cpp
  src/cnglob.h
  src/cnguts.cpp
  src/dmpak.cpp
  src/envpak.cpp
Labels: enhancement, multi-platform

#341 Remove sys_nerr and sys_errlist.
  src/messages.cpp
Labels: multi-platform

#325 Rename filename comments
  src/CMakeLists.txt
  src/RCDEF/rcdef.cpp
  src/ancrec.h
  src/cnah1.cpp
  src/cncult4.cpp
  src/cnguts.h
  src/cprint.h
  src/cse.cpp
  src/cul.cpp
  src/dhwcalc.cpp
  src/dhwsolar.cpp
  src/envpak.cpp
  src/foundation.cpp
  src/foundation.h
  src/geometry.cpp
  src/impf.h
  src/messages.h
  src/srd.h
  src/xiopak.cpp
  src/xiopak.h
  src/xmodule.h
Labels: maintenance
