Repository cse-sim/cse, pull requests merged in 2022-05, with the labels that each got.

#184 Add a template for new Pull Requests
  .github/pull_request_template.md
Labels: enhancement

#252 Make AIRHANDLER autosized heat pump capacities consistent
  doc/src/records/airhandler.md
  src/CMakeLists.txt
  src/CNAH1.CPP
  src/CNCOIL.CPP
  src/CNCULT.CPP
  src/CNCULT5.CPP
  src/CNLOADS.CPP
  src/CNRECS.DEF
  src/HVAC.CPP
  src/HVAC.H
  src/PSYCHRO.CPP
  src/PSYCHRO.H
Labels: enhancement

#258 Add Heat Recovery to AIRHANDLER
  doc/src/records/airhandler.md
  src/CGCOMP.CPP
  src/CMakeLists.txt
  src/CNAH1.CPP
  src/CNAH2.CPP
  src/CNCULT.CPP
  src/CNCULT5.CPP
  src/CNRECS.DEF
  src/NUMMETH.H
  src/RCDEF.CPP
  src/nummeth.cpp
  test/Multifamily-DOAS.cse
Labels: enhancement, building science, 3 - high priority

#261 Remove ahccCapSRat requirement when not AUTOSIZING
  doc/src/records/airhandler.md
  src/CNCOIL.CPP
  src/CNCULT5.CPP
Labels: enhancement, 3 - high priority

#263 Remove AUTOSIZE preprocessor as if defined
  src/CNAH1.CPP
  src/CNAH2.CPP
  src/CNCOIL.CPP
  src/CNCULT.CPP
  src/CNCULT2.CPP
  src/CNCULT5.CPP
  src/CNDEFNS.H
  src/CNFAN.CPP
  src/CNGUTS.CPP
  src/CNZTU.CPP
  src/CUEVAL.CPP
  src/CUL.CPP
  src/CUL.H
  src/CUPARSE.CPP
  src/CUPROBE.CPP
  src/CUTOK.H
  src/EXMAN.CPP
  src/RCDEF.CPP
Labels: maintenance, 2 - medium priority

#267 Modify AIRHANDLER coil airflow warnings
  src/CNCOIL.CPP
  src/CNDTYPES.DEF
  src/MSGTBL.CPP
Labels: maintenance

#264 Modify cmake to allow for other platform to compile.
  cmake/preprocess.cmake
  src/CMakeLists.txt
Labels: enhancement, multi-platform

#271 Add heat recovery outputs to AH report
  src/CGRESULT.CPP
  src/CNAH1.CPP
  src/CNAH2.CPP
  src/CNLOADS.CPP
  src/CNRECS.DEF
  src/CNZTU.CPP
  test/ref/2ZONE.REP
  test/ref/600.REP
  test/ref/930.REP
  test/ref/960.REP
  test/ref/AUTOSIZE.REP
  test/ref/CRTERMINALAH.REP
  test/ref/FRESNO.REP
  test/ref/MASSTEST1.REP
  test/ref/MF8X.REP
Labels: enhancement

#276 Remove extra qualification in calendar constructor.
  src/TDPAK.H
Labels: maintenance, multi-platform

#229 User input subhrticks
  doc/src/records/top-members.md
  src/CNCULT.CPP
  src/CNCULT2.CPP
  src/DHWCalc.cpp
Labels: enhancement, 2 - medium priority
