Repository cse-sim/cse, pull requests merged in 2022-07, with the labels that each got.

#309 Add git-hooks to manage submodules by default
  cmake/initialize-submodules.cmake
Labels: maintenance

#282 Rcdef multiplatform upgrade
  src/rcdef.cpp
  src/xiopak.cpp
  src/xiopak.h
Labels: enhancement, multi-platform

#308 Remove forscope pragma
  src/ancrec.cpp
  src/ancrec.h
  src/brfw.cpp
  src/cnah1.cpp
  src/cnah2.cpp
  src/cncult5.cpp
  src/cncult6.cpp
  src/cnglob.h
  src/cnhp.cpp
  src/cntp.cpp
  src/cuprobe.cpp
  src/datfcns.cpp
  src/exman.cpp
  src/pp.cpp
  src/strpak.cpp
Labels: maintenance, multi-platform

#266 Update CNGLOB for multi-platform
  src/cnglob.h
  src/vecpak.h
Labels: enhancement, multi-platform

#317 Change _snprintf for snprintf
  src/exman.cpp
Labels: maintenance, multi-platform

#256 Replace windows string compare function
  src/RCDEF/rcdef.cpp
  src/ancrec.cpp
  src/ashwat.cpp
  src/cgsolar.cpp
  src/cncult2.cpp
  src/cncult4.cpp
  src/cse.cpp
  src/cul.cpp
  src/cuparse.cpp
  src/cuprobe.cpp
  src/cvpak.cpp
  src/impf.cpp
  src/lookup.cpp
  src/pp.cpp
  src/strpak.cpp
  src/strpak.h
  src/sytb.cpp
  src/tdpak.cpp
  src/vrpak.cpp
  test/unit/CMakeLists.txt
  test/unit/strpak.unit.cpp
Labels: enhancement, 2 - medium priority, multi-platform

#314 Ashface upgrade
  src/rmkerr.h
Labels: maintenance, multi-platform

#275 Remove "NEAR" and "FAR"
  src/RCDEF/rcdef.cpp
  src/ancrec.cpp
  src/brfw.cpp
  src/cgcomp.cpp
  src/cgdebug.cpp
  src/cgresult.cpp
  src/cnah2.cpp
  src/cncult3.cpp
  src/cnguts.cpp
  src/cnztu.cpp
  src/cpgbuild.cpp
  src/cpnat.cpp
  src/cse.h
  src/cueval.cpp
  src/cueval.h
  src/cul.cpp
  src/cul.h
  src/cuparse.cpp
  src/cuparsei.h
  src/cuparsex.h
  src/cuprobe.cpp
  src/cvpak.cpp
  src/envpak.cpp
  src/exman.cpp
  src/gmutil.cpp
  src/messages.cpp
  src/msgtbl.cpp
  src/pgpak.cpp
  src/pp.cpp
  src/rmkerr.cpp
  src/solar.cpp
  src/sytb.cpp
  src/wfpak.cpp
  src/xiopak.cpp
Labels: enhancement, multi-platform
